[tools]

# Programming Language Environments
python = "latest"
rust = "latest"
java = "temurin"
node = "latest"

# Neovim
neovim = "0.11"
tree-sitter = "latest"
gdu = "latest"
bottom = "latest"
lazygit = "latest"
